### ISSUE TITLE
Keyboard Shortcuts - Add opt-in option 

### ISSUE THREAD

**Issue by superlinkx** [twinnydotdev/twinny#220]
**Describe the bug**
Having shortcuts that use ctrl+shift+t as a chord cause the commonly bound `ctrl+shift+t` shortcut to be overwritten as the start of a chord, breaking reopening a closed tab by default.

**To Reproduce**
1. Use default keybinds
2. Close an open tab
3. Press `ctrl+shift+t`
4. Note that at the bottom of the editor, VS Code is waiting for the rest of a chord
5. Closed tab won't reopen

**Expected behavior**
Existing keybind should be respected, and by default that means it should reopen a closed editor tab

**Desktop (please complete the following information):**
 - OS: Windows 11 and WSL 2 Ubuntu 22.04
 - Browser: N/A
 - Version: VS Code v1.88.1 with Twinny v3.11.19
 
**Additional context**
It may be wise to not create keyboard shortcuts by default and let users opt-in

**Comment by rjmacarthy** [comment]
Hey thanks for the report, sorry about that!  I just updated the keyboard shortcuts to not override any defaults.  Opt-in would require more work and I'm too lazy at the moment to work on it :). 

Many thanks,

**Comment by superlinkx** [comment]
Appreciate all the work you do, I've been loving this extension otherwise!

**Comment by rjmacarthy** [comment]
I removed some short cuts which could overwrite the defaults.
