### ISSUE TITLE
Keyboard short cut: accept part of the FIM suggestion

### ISSUE THREAD

**Issue by Fadelis98** [twinnydotdev/twinny#223]
**Is your feature request related to a problem? Please describe.**

When the FIM give a long suggestion, usually I only want to accept some begining words. In github copilot, I can press `ctrl →` to accept only one word each time, just like I'm editing some existing line, and begin to type at any place. For multiline suggestions, I can press `end` to accpt the current line only as well.

**Describe the solution you'd like**
add support for common cursor control shortcuts

**Comment by rjmacarthy** [comment]
Hey @Fadelis98 this should already work, have you tried it?

**Comment by rjmacarthy** [comment]
OK, I did some digging, this is somehow broken on Linux maybe Mac on later vscode versions.  When I updated to insiders and tested it, it starts to work again. https://code.visualstudio.com/insiders/ when the new version is released it'll be fixed.

**Comment by rjmacarthy** [comment]
Please try latest insiders version of vscode. Many thanks.
