### ISSUE TITLE
feat: open new chat window in new editor tab

### ISSUE THREAD

**Issue by hitzhangjie** [twinnydotdev/twinny#232]
**Is your feature request related to a problem? Please describe.**
Hope twinny could open new chat window in new editor tab. Github copilot has this feature, so I can open it quickly. And I don't mess up the others' QA area.

**Describe the solution you'd like**
Just like Github copilot pro，we could do like this:
![image](https://github.com/rjmacarthy/twinny/assets/3725760/878ffb52-103e-40ec-b9ce-ee21cf9c0c8a)

**Comment by rjmacarthy** [comment]
Thanks for the great suggestion, I'm not sure what is involved at the moment and it needs further investigation.

**Comment by rjmacarthy** [comment]
Hey @hitzhangjie sorry about the delay, I don't have a lot of time to work on this and other things took precedence. I just released `v3.17.5` which includes this change :)
