### ISSUE TITLE
Edit and re-submit in chat mode

### ISSUE THREAD

**Issue by PkmX** [twinnydotdev/twinny#233]
**Is your feature request related to a problem? Please describe.**
In chat mode, it is not unusual that you have to refine or re-phrase the message you sent because the AI doesn't quite understand the prompt. Right now this requires the user to clarify in a follow-up question (which eats your context limit and potentially confuses less-capable LLMs) or start a new conversation entirely (need to retype or copy/paste the entire history leading up to the message you want to edit).

**Describe the solution you'd like**
Add an edit button to each message that allows you to edit and re-submit. This feature is already present in many other chat UIs.

**Comment by ChrisDeadman** [comment]
Gradio provides a `ChatInferface' that looks like this:
![image](https://github.com/rjmacarthy/twinny/assets/8740325/afd0afd6-fdc4-4890-b78c-fa75ba677cf9)

And I have to say, after getting used to the `Undo`(remove response from model, remove user message, put removed user message back into input textbox to allow editing) and `Redo` (regenerate response from model) I found it to be much more useful and intuitive than the way ChatGPT lets you edit a previous message.

Maybe two simple `undo` and `redo` buttons could do it?

**Comment by PkmX** [comment]
Either way seems fine for me. The clear button would be useful as well since sometimes I just want to ask a quick question without cluttering the conversation history.

**Comment by rjmacarthy** [comment]
Thanks for the great suggestion, so are we referring to only the last submitted message for editing or individual messages inside the conversation history? 

Many thanks.

**Comment by ChrisDeadman** [comment]
For me any of the solutions would be fine

**Comment by rjmacarthy** [comment]
Your wish is now my command!  Please checkout 3.15.0 and provide some feedback, thanks all!
