### ISSUE TITLE
Configured providers but twinny not sending any requests to provider.

### ISSUE THREAD

**Issue by Duoquote** [twinnydotdev/twinny#242]
**Describe the bug**
I have setup the following providers and I checked with curl that /api/generate endpoint on http://duodesk.duo:11434 works, the extension shows loading circle but is not sending any requests. Also tried setting Ollama Hostname setting to duodesk.duo, but no luck.

**To Reproduce**
Just added the providers I have attached.

**Expected behavior**
Should work with the providers I have I think?

**Screenshots**
![image](https://github.com/rjmacarthy/twinny/assets/16341937/38f53671-e650-443c-b78c-4cb72fd047ab)

**Logging**
Logging is enabled but not sure where am I supposed to see the logs, checked Output tab but there is no entry for twinny.

**API Provider**
Ollama running at http://duodesk.duo:11434 in local network.

**Chat or Auto Complete?**
Both

**Model Name**
codellama:7b-code

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Additional context**

**Comment by Duoquote** [comment]
I was looking at other issues and saw where I could see the logs, the log is as follows:
![image](https://github.com/rjmacarthy/twinny/assets/16341937/71a32dac-39b0-44d7-b1ac-4609c7450ee4)

Looks like hostname is set incorrectly, how do I change it?

**Comment by rjmacarthy** [comment]
Maybe try a restart? The settings look correct to me.

**Comment by randomeduc** [comment]
How can I check some logs? Because I have the same problem on Windows, I'm running VS Code from WSL:Ubuntu

1. Install Ollama and check if is running at `http://localhost:11434`
 
![imagen](https://github.com/rjmacarthy/twinny/assets/39845488/5bd215f0-4b66-4968-af3c-f57529d466b1)

2. Install the models
![imagen](https://github.com/rjmacarthy/twinny/assets/39845488/5bc8d886-96c6-43fb-87f6-8f959f4f069c)

3. Install and configure the vscode extension
Settings
![imagen](https://github.com/rjmacarthy/twinny/assets/39845488/9ff764b9-2762-425f-ab79-ba63458ee247)

Providers
![imagen](https://github.com/rjmacarthy/twinny/assets/39845488/3344f5da-f850-4c0c-9a83-3ccafd8ceabe)

4. Test the chat
![imagen](https://github.com/rjmacarthy/twinny/assets/39845488/68ce7a47-7cca-4590-bc4a-2177a4f6dcdd)

But the loading spinner keep there, any help?

**Comment by jpaveg** [comment]
Having the same issue. Continue extension works, but I can't get Twinny to work.

```js
ERR [Extension Host] Fetch error: TypeError: fetch failed
	at node:internal/deps/undici/undici:12345:11
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.streamResponse (/home/user/.vscode-server/extensions/rjmacarthy.twinny-3.11.45/out/index.js:2:138539)
console.ts:137 [Extension Host] Fetch error: TypeError: fetch failed
	at node:internal/deps/undici/undici:12345:11
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.streamResponse (/home/user/.vscode-server/extensions/rjmacarthy.twinny-3.11.45/out/index.js:2:138539)
y @ console.ts:137
```

**Comment by changty** [comment]
I have Twinny 3.12.0 on Linux. I'm running ollama with mistral-nemo and stable-code. 
Curling the ollama works fine but Twinny just keeps spinning the circle, like in the screenshots above. 
My project is running in a docker container, but that should not affect Twinny. 

 I do get a similar error message as above. 
 
 `  ERR [Extension Host] Fetch error: TypeError: fetch failed
	at node:internal/deps/undici/undici:12345:11
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async streamResponse (/root/.vscode-server/extensions/rjmacarthy.twinny-3.12.0/out/index.js:20901:22)`
	
Any suggestions on how to fix this?

**Comment by unclemusclez** [comment]
i also just noticed this, i am using vscodium.

tbh i dont think this was always the case so i will update when i figure it out, hopefully.

**Comment by unclemusclez** [comment]
https://stackoverflow.com/questions/70590704/fetching-in-a-vscode-extension-node-fetch-and-nodehttp-issues

> Judging from these two issues:
> 
> [Cannot find module 'node:http` on AWS Lambda v14](https://github.com/node-fetch/node-fetch/issues/1367) and
> [Problem with importing node-fetch v3.0.0 and node v16.5.0](https://github.com/node-fetch/node-fetch/issues/1266)
> 
> it looks like the upgrade from node-fetch v3 to v3.1 was "troublesome" and resulted in the error you are seeing for some.
> 
> A few users are downgrading to v2 (or you might try v3 rather than v3.1 which you are using).
> 
> Uninstall node-fetch and npm install -s node-fetch@2

**Comment by pacman100** [comment]
Facing the same issue. Any updates?

**Comment by disarticulate** [comment]
localhost and 0.0.0.0 not working for me. Have a responding ollama on both my local machine and remote.

UI responds "==## ERROR ##== : fetch failed"

In devtools, no requests are made, so I assume its on the backend.

The last error says:
```
ERR [Extension Host] [91m [ERROR_twinny] [32m Message: Fetch error 
 [91m Error Type: TypeError 
  Error Message: fetch failed 
 [31m TypeError: fetch failed
	at node:internal/deps/undici/undici:13392:13
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async globalThis.fetch (file:///home/cy/.vscode-server/bin/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:159:19800)
	at async streamResponse (/home/cy/.vscode-server/extensions/rjmacarthy.twinny-3.19.23-linux-x64/out/index.js:58388:22)
console.ts:137 [Extension Host]  [ERROR_twinny]  Message: Fetch error 
```
error goes here: https://github.com/twinnydotdev/twinny/blob/d528d53caae5b556dff2a541600046bdb0c0fe61/src/extension/api.ts#L103

The fetch config from the stream response:
```
[Extension Host] [twinny] ***Twinny Stream Debug***
    Streaming response from 0.0.0.0:11434.
    Request body:
    {
  "model": "llama3.1:latest",
  "stream": true,
  "messages": [
    {
      "role": "user",
      "content": "yhello"
    },
    {
      "role": "assistant",
      "content": "==## ERROR ##== : fetch failed"
    },
    {
      "role": "user",
      "content": "\n  Generate a title for this conversation in under 10 words.\n  It should not contain any special characters or quotes.\n"
    }
  ],
  "keep_alive": "5m",
  "options": {
    "temperature": 0.2,
    "num_predict": 2048
  }
}

    Request options:
    {
  "hostname": "0.0.0.0",
  "port": 11434,
  "path": "/api/chat",
  "protocol": "http",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": "Bearer undefined"
  }
}
```
I can't see in ollama API but "Authorization" header should be excluded if it's undefined.  Looks like there's several files setting Authorization to "Bearer undefined". 

Added a pull request here: https://github.com/twinnydotdev/twinny/pull/422 there's several other files using the fetch.

I don't think it's the actual error though.

**Comment by disarticulate** [comment]
I just noticed though, my project is using SSH, and this plugin is being installed on the SSH vscode server, which isn't going to have access. That's definitely an error. It should probably be installed locally unless otherwise indicated.

**Comment by disarticulate** [comment]
> I just noticed though, my project is using SSH, and this plugin is being installed on the SSH vscode server, which isn't going to have access. That's definitely an error. It should probably be installed locally unless otherwise indicated.

This is definitely _a_ problem. I opened up a local workspace and it connects. I'm going to open a specific issue.

**Comment by unclemusclez** [comment]
> localhost and 0.0.0.0 not working for me. Have a responding ollama on both my local machine and remote.
> 
> UI responds "==## ERROR ##== : fetch failed"
> 
> In devtools, no requests are made, so I assume its on the backend.
> 
> The last error says:
> 
> ```
> ERR [Extension Host] �[91m [ERROR_twinny] �[32m Message: Fetch error 
>  �[91m Error Type: TypeError 
>   Error Message: fetch failed 
>  �[31m TypeError: fetch failed
> 	at node:internal/deps/undici/undici:13392:13
> 	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 	at async globalThis.fetch (file:///home/cy/.vscode-server/bin/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:159:19800)
> 	at async streamResponse (/home/cy/.vscode-server/extensions/rjmacarthy.twinny-3.19.23-linux-x64/out/index.js:58388:22)
> console.ts:137 [Extension Host]  [ERROR_twinny]  Message: Fetch error 
> ```
> 
> error goes here:
> 
> https://github.com/twinnydotdev/twinny/blob/d528d53caae5b556dff2a541600046bdb0c0fe61/src/extension/api.ts#L103
> 
> The fetch config from the stream response:
> 
> ```
> [Extension Host] [twinny] ***Twinny Stream Debug***
>     Streaming response from 0.0.0.0:11434.
>     Request body:
>     {
>   "model": "llama3.1:latest",
>   "stream": true,
>   "messages": [
>     {
>       "role": "user",
>       "content": "yhello"
>     },
>     {
>       "role": "assistant",
>       "content": "==## ERROR ##== : fetch failed"
>     },
>     {
>       "role": "user",
>       "content": "\n  Generate a title for this conversation in under 10 words.\n  It should not contain any special characters or quotes.\n"
>     }
>   ],
>   "keep_alive": "5m",
>   "options": {
>     "temperature": 0.2,
>     "num_predict": 2048
>   }
> }
> 
>     Request options:
>     {
>   "hostname": "0.0.0.0",
>   "port": 11434,
>   "path": "/api/chat",
>   "protocol": "http",
>   "method": "POST",
>   "headers": {
>     "Content-Type": "application/json",
>     "Authorization": "Bearer undefined"
>   }
> }
> ```
> 
> I can't see in ollama API but "Authorization" header should be excluded if it's undefined. Looks like there's several files setting Authorization to "Bearer undefined".
> 
> Added a pull request here: #422 there's several other files using the fetch.
> 
> I don't think it's the actual error though.

are you using the ollama template with an openai endpoint, or vice-versa?

**Comment by rjmacarthy** [comment]
Please let me know if we should re-open, thanks!

**Comment by disarticulate** [comment]
> are you using the ollama template with an openai endpoint, or vice-versa?

No. I'm fairly certain this is an issue related to the plugin installing in the SSH workspace which _doesn't_ have access to my localhost run Ollama. see https://github.com/twinnydotdev/twinny/issues/423 for what the most likely cause is of multiple error reports.

The work around at the moment for SSH workplace is to provide a IP and open port to the ollama server if you're working on remote; or use a local code source. It might be possible in the open ports section, but I don't know if that's two-way; I think it's just a one way, but don't know how the plugin is establishing the connection.

**Comment by crrrazyden** [comment]
I have VSCode connected via SSH to a remote machine. I install the provider for Twinny and specify the host example.host. After that, the chat works and I get responses, but FIM doesn't work. It sends requests to:
```js
getDefaultFimProvider() {
  return {
    apiHostname: "0.0.0.0",
    apiPath: "/api/generate",
    apiPort: 11434,
    apiProtocol: "http",
    fimTemplate: FIM_TEMPLATE_FORMAT.codellama,
    label: "Ollama FIM",
    id: uuidv4(),
    modelName: "codellama:7b-code",
    provider: API_PROVIDERS.Ollama,
    type: "fim"
  } as TwinnyProvider
}
```

Log:
```log
   Request options:
    {
  "hostname": "0.0.0.0",
  "port": 11434,
  "path": "/api/generate",
  "protocol": "http",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": ""
  }
}

    Number characters in all messages = 0
[ERROR_error] Fetch error
  Error Type: TypeError
  Error Message: fetch failed
```

Fim-provider settings:

![Image](https://github.com/user-attachments/assets/886ebcdf-c1d9-4ab2-8925-bbd33273b1d5)
