### ISSUE TITLE
Add support for VSCode 1.70.x again please 

### ISSUE THREAD

**Issue by imClumsyPanda** [twinnydotdev/twinny#264]
Hi, thanks for developing the amazing extension!

I’m now requested to use VSCode version not newer than 1.70.x, while twinny not newer than v2.6.21 supported VSCode 1.70.x, making new features not available any more. Would you please add support for lower VSCode version again?

**Comment by rjmacarthy** [comment]
Please could you provide more instructions as to what is not supported, many thanks.

**Comment by imClumsyPanda** [comment]
@rjmacarthy thanks a lot for the quick reply! In version v2.26.1, only ollama is allowed to be provider, while custom OpenAI api like LMStudio or some other type of local custom OpenAI api is needed. I'd like to try the newest version of twinny but it's not competitive for vscode 1.70.x

**Comment by rjmacarthy** [comment]
Hmm, that is not correct you can configure many different providers in the latest version.  Please check the docs.  Many thanks.
