### ISSUE TITLE
undefined with deepseek-lite-ggml and llama.cpp

### ISSUE THREAD

**Issue by micsthepick** [twinnydotdev/twinny#266]
**Describe the bug**
any call to the chat completion api in llama.cpp returns a string of "undefined" with the DeepSeek-Coder-V2-Lite-Instruct-Q6_K.gguf model

**To Reproduce**
Download the model, run with the following command:
`./llama-server -ngl 99 --ctx-size 16384 -m models/DeepSeek-Coder-V2-Lite-Instruct/DeepSeek-Coder-V2-Lite-Instruct-Q6_K.gguf`
, add a chat provider for llamacpp at localhost:8080/v1/chat/completions.

**Expected behavior**
undefined is NOT repeated and the generated text makes at least some level of sense

**Screenshots**
![image](https://github.com/twinnydotdev/twinny/assets/11528421/7790e163-0334-4c23-966f-9e4ea2fedd19)

**Logging**
[logs.txt](https://github.com/user-attachments/files/16094625/logs.txt)

**API Provider**
as above, llama.cpp default port on localhost:8080/v1/chat/completions

**Chat or Auto Complete?**
chat

**Model Name**
DeepSeek-Coder-V2-Lite-Instruct-Q6_K.gguf

**Desktop (please complete the following information):**
 - OS: Windows 11 Edu
 - Browser N/A

**Additional context**

**Comment by Raizo62** [comment]
Hi

And if you set as Provider the value "ollama" (instead of "llamacpp", even if you use llama.cpp) ?
