### ISSUE TITLE
This plugin creates keybindings for CTRL+SHIFT+Z which felt like it broke undo redo 

### ISSUE THREAD

**Issue by spirobel** [twinnydotdev/twinny#277]
**Describe the bug**
This plugin creates keybindings for CTRL+SHIFT+Z which felt like it broke undo redo 

**To Reproduce**
undo redo with shortcuts before and after activating this plugin

**Expected behavior**
not overwrite default shortcuts that are used everywhere for undo redo

I fixed this for me by changed the shortcuts, but it led me to disable the plugin for a while until I figured out a solution.

Anyway thank you very much for providing us with this great tool.
You are a gem.

**Comment by rjmacarthy** [comment]
Hey, what do you suggest as an alternative?  Many thanks.

**Comment by spirobel** [comment]
I will think  about it. How do you picture the shortcut should work?
It is to open the sidebar, right?

**Comment by rjmacarthy** [comment]
Hey, for now I removed the code overwriting the defaults, users can define their own.

Many thanks.
