### ISSUE TITLE
Add search results to the chat

### ISSUE THREAD

**Issue by spirobel** [twinnydotdev/twinny#279]
**Is your feature request related to a problem? Please describe.**
I am mostly using phind instead of the code chat, because it does not contain search results.
Currently mostly depend on this plugin for FIM.

**Describe the solution you'd like**
Add search results to the chat.
Just saw this has been open sourced: **https://x.com/KhazzanYassine/status/1819787693330399344** can maybe be a source of inspiration

Thank you  for your work. The plugin is useful as is, but search result rag would really make it take off I think.

**Comment by rjmacarthy** [comment]
Hey @spirobel thanks for the suggestion it's in the works. It takes me a long time to release things since I have full time work commitments alongside this plugin. I have an end to end solution working now it just needs some refinement before production release. It's coming soon. Many thanks.

**Comment by spirobel** [comment]
Amazing!
>It's also worth to mention that Ollama doesn't have a re-ranking model and the vector database needs to be running inside vscode, 

An alternative would be to use simple keyword search and a prompt to rerank. (also makes it easier to debug, because humans can read keywords, but not vectors)
I remember reading an article comparing keyword search to vector search in the RAG usecase and it came to the conclusion that keyword search works just as good and even better in some search cases.

**Comment by rjmacarthy** [comment]
Added support in version 3.13.3.
