### ISSUE TITLE
Extension does not start

### ISSUE THREAD

**Issue by sharkshark123** [twinnydotdev/twinny#285]
**Describe the bug**
Extension does not start. 

** Step to reproduce **
I am running on MacbookPro M3 Max,  OS: Sonoma 14.5
ollama version 0.3.4, pull the following models (codellama:7b-code, codellama:7b-instruct),
 I am running VSCode 1.92.0, installed twinny extension (version 3.13.20).
Restart VSCode, click the twinny icon on the sidebar, and the twinny extension display a blue progress bar.

From VSCode output, it said 
Activating extension rjmacarthy.twinny failed due to an error:
Error: Cannot find module '@lancedb/lancedb-darwin-arm64'

**Screenshots**
Screenshot of VSCode, showing extension is loading, and the error output.
<img width="1608" alt="Screenshot 2024-08-10 at 2 10 49 PM" src="https://github.com/user-attachments/assets/e42152ec-5142-4e26-8180-f7eccf1a8138">

**Desktop (please complete the following information):**
 - OS: Sonoma 14.5

**Comment by rjmacarthy** [comment]
Hey, I messed up th GitHub actions for this arch. I just made a hacky release to attempt to fix it. Please could you try for.me? Thanks.

**Comment by sharkshark123** [comment]
Thanks for the update. It works now.

**Comment by zh012** [comment]
This same issue happens on version 3.14.2.

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/7bdc3609-57dd-4b91-8987-e14e2d75e356">

**Comment by joxxoxo** [comment]
Same for me (M2 max). The latest working version is 3.12.6, nothing newer is working

**Comment by rjmacarthy** [comment]
Hello, @joxxoxo and @zh012 please could you check the extension folder for me and try to find thr native module for lancedb in there? Thanks.

**Comment by rjmacarthy** [comment]
Hello @joxxoxo and @zh012 I published version v3.14.7 which should fix the issues, please report back, many thanks.

**Comment by joxxoxo** [comment]
@rjmacarthy v3.14.7 works 🙌  
Thank you!
