### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by viktorg1** [twinnydotdev/twinny#301]
Type: <b>Bug</b>

Nothing works on extension

Extension version: 3.15.4
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux x64 6.8.0-40-generic snap
Modes:

**Comment by rjmacarthy** [comment]
Hello, please could you provide more information e.g error messages, notifications?
