### ISSUE TITLE
Can't select any model if Ollama has a long list of models

### ISSUE THREAD

**Issue by JamesClarke7283** [twinnydotdev/twinny#302]
**Describe the bug**
If i have a large number of models on my ollama instance, it will only show me the top 8 or something, i can't scroll down to see more models.

**To Reproduce**
Install many models, like 10 on a ollama server. and edit providers.

**Expected behavior**
Should be a scrollbar, to see more models.

**Screenshots**
![Screenshot_2024-08-27_12-28-57](https://github.com/user-attachments/assets/b2bfe8d7-9794-4c61-83aa-d13c8619173b)

**Logging**
N/A

**API Provider**
Ollama

**Chat or Auto Complete?**
N/A this happens with any model list.

**Model Name**
N/A any model

**Desktop (please complete the following information):**
 - OS:  Archlinux
 - Browser Brave
 - Twinny Version 3.15.6

**Additional context**
Its a regression... on 3.14.7, it has the scrollbar.

**Comment by rjmacarthy** [comment]
Hey, when I tested it I could see all my models in there?

![image](https://github.com/user-attachments/assets/d8fd6ca2-16b5-4db1-a229-d1a9056c8a19)
