### ISSUE TITLE
Revise icons / customizable icons

### ISSUE THREAD

**Issue by matthiasgeihs** [twinnydotdev/twinny#305]
**Is your feature request related to a problem? Please describe.**
I like twinny, but i find the icons a bit distracting.
- The twinny icon in the status bar is a colorful emoticon 🤖 whereas the rest of the VSCode UI is typically very minimal and black and white.
- The twinny icon in the side bar is ok, but some lines are a bit too thick to fall into place with the rest.

(Icons in my IDE are very important to me as they are visible all the time and as a programmer I'm very much conscious about having the most clean possible environment around the code I write.)

**Describe the solution you'd like**
- Either revise icons to fit perfectly within the VSCode UI. (Use black and white icon in the status bar. Use thinner lines for the icon in the side bar.)
- Or make it easy for users to customize the icons.

**Comment by rjmacarthy** [comment]
Hey @matthiasgeihs in the latest version (3.15.9) I removed the use of robot icon for built in editor icons, hope that helps.

**Comment by matthiasgeihs** [comment]
Hey @rjmacarthy, thx for addressing my comment. Hope it didn't sound rude. Just my opinion, but thought I put it out there to see if others feel the same. I'll have a look at the updated version. Thx!
