### ISSUE TITLE
Chat not "understanding" Ollama streaming.

### ISSUE THREAD

**Issue by arale61** [twinnydotdev/twinny#308]
**Describe the bug**
Twinny displaying "**Sorry, I don’t understand. Please try again.**" (**EMPTY_MESSAGE**) constantly.
I've reset to defaults providers, before was working with "llama3.1:latest" without problems.
One day stop working and repeats all the time the mentioned message.
From my understanding Twinny is expecting to receive message of type "**ServerMessage**" and receives "**StreamResponse**".
I've inspected loopback packages to confirm. Ollama is responding correctly but using streaming.
Twinny client requests with "stream:True", see sample of request:

POST /api/chat

{"model":"codellama:7b-instruct","stream":true,"messages":[{"role":"system","content":"You are a helpful, respectful and honest coding assistant.\nAlways reply using markdown.\nBe clear and concise, prioritizing brevity in your responses.\nFor code refactoring, use markdown with appropriate code formatting."},{"role":"user","content":"hi"}],"keep_alive":"5m","options":{"temperature":0.2,"num_predict":512}}

Sample of response:

{"model":"codellama:7b-instruct","created_at":"2024-09-10T19:57:12.559786673Z","message":{"role":"assistant","content":"Hi"},"done":false}
...
{"model":"codellama:7b-instruct","created_at":"2024-09-10T19:57:12.843520298Z","message":{"role":"assistant","content":""},"done_reason":"stop","done":true,"total_duration":1527308005,"load_duration":1152613618,"prompt_eval_count":70,"prompt_eval_duration":47716000,"eval_count":19,"eval_duration":283658000}

From the observer HTTP Stream I can confirm Ollama did receive and responded correctly to the request.

I can't see where I can **set in Twinny to "stream: true" for chat.**

I'd reinstalled extension but problem persists.

**To Reproduce**
N/A

**Expected behavior**
Handle the ollama response as StreamResponse not ServerMessage.

**Screenshots**

![Screenshot from 2024-09-10 22-07-10](https://github.com/user-attachments/assets/ca12f3fd-0787-4fa3-a545-7cde024ffd93)

**Logging**
Rnable logging in the extension settings if not already enabled (you may need to restart vscode if you don't see logs).  Proivide the log with the report.

**API Provider**
Ollama

**Chat or Auto Complete?**
Is this a problem with chat or fim (auto-complete)?
Chat

**Model Name**
Provide the model name you are using e.g `codellama:7b-code` or `codellama:7b-instruct`

**Desktop (please complete the following information):**
debian 12

**Additional context**

**Comment by arale61** [comment]
For some reason I had "/api/chat" in the provider path instead of "/v1/chat/completions".
I don't remember to have changed the path, anyways, I close the issue.

**Comment by rjmacarthy** [comment]
Hey, thanks for the report. It was actually an issue I caused last week. I've fixed it now, thanks again for pointing it out!!

**Comment by arale61** [comment]
> Hey, thanks for the report. It was actually an issue I caused last week. I've fixed it now, thanks again for pointing it out!!

Thanks to you for providing wonderful extension!
I'm Happy that the report helped then.
:-)
