### ISSUE TITLE
Custom Templates not working with 3.17

### ISSUE THREAD

**Issue by unclemusclez** [twinnydotdev/twinny#323]
![image](https://github.com/user-attachments/assets/86b4bf85-9d00-4b35-a0d2-56d8dc45a6c7)

If I downgrade to Twinny 3.16.* i have no issues with the templates. As of the most recent update, it will only trigger the system message, it does not actually prompt the model.

I am using Gemma 2 27b with the ollama 0.3.11

**Comment by rjmacarthy** [comment]
Thanks for reporting! 

I just added a quick fix for it. It's unfortunate this happened now because I can hardly stay awake suffering from covid19 😢
