### ISSUE TITLE
Utilizing Open WebUI Embeddings with Ollama i.e., `/ollama/v1/embeddings`

### ISSUE THREAD

**Issue by unclemusclez** [twinnydotdev/twinny#324]
Is this possible? When i try to configure this is it will automatically revert to my original Ollama settings in the menu.

TBH I dont even really understand how to conceptualize about this. I'd like them to utilize the same vector database if possible, and when i add embeddings via twinny or open webui, it should go into the same place.

i don't know if this is a good idea or possible. Any feedback would be really helpful.

**Comment by arttraratatr** [comment]
So you mean you would like to leverage open webUI's RAG feature in twinny?

**Comment by arttraratatr** [comment]
@unclemusclez 

I am curious. If open webUI requires login to use, can you still set it up in as Twinny provider and get it work with chatting? How? I mean regular chat not RAG.

**Comment by arttraratatr** [comment]
@arttraratatr 

How did you get openwebUI RAG work through Twinny? Its knowledge used by # seem not working in Twinny chat panel.
