### ISSUE TITLE
Deafult Embedding Option Auto-Reverts

### ISSUE THREAD

**Issue by unclemusclez** [twinnydotdev/twinny#334]
I've noticed that within connections, unless I change the default embedding profile to the settings I desire, I can not get my embedding profile connections to stick (i am running open-webui behind a reverse proxy and there may be some issues with timeouts I did not foresee, of which i am currently looking into. This may have pertained to my other ticket, and i might be mixing together 2 or 3 issues here. 1, my proxy, 2, new open-webui API settings, and 3, sticky embedding profile settings--this ticket.) 

In these examples, i am not connecting via reverse-proxy. its a direct port connection.

I'm not sure if this is a graphical glitch, a connection detection issue, or the embedding API being placed incorrectly (at this point I've tried multiple verified combinations, with OpenUI and Ollama), however, if i generate a NEW connection, or DUPLICATE a connection, and put in new embedding settings, it will revert to the original embedding connection in the connection selector, even if the default profile it is deleted. it will just show up as a blank profile name, and not use the option i created in the pull-down.

if i just edit the original connection, the settings work and it contacts the server, just with errors, at least for open-webui. this part is probably me... but i do think there is connection profile issue for embedding that might be influencing my confusion. 

just to maybe frame some of what i am doing: i was using all of this locally and i'm migrating everything to an inference machine. I had embedding set up locally with my machine, separate from open-webui. with the new machine, i want all the context under one roof.

![image](https://github.com/user-attachments/assets/a570c8d2-28b6-4b4d-9c85-e50cac5c0685)
![image](https://github.com/user-attachments/assets/b1189517-503a-42be-a220-42e9e17498da)
![image](https://github.com/user-attachments/assets/60e5831a-f751-4de0-9500-d5cb1f3515c3)
Ollama Embedding was the original default profile where i changed the settings. even if it does not connect properly, as identified in the other ticket, it reverts to this connection automatically, despite an alternative working ollama connection available/selected.
Seems also the menu is organized alphabetically.
My embedding connections:
![image](https://github.com/user-attachments/assets/b57d72a3-7075-4861-a3bf-0165d3b375a9)

**Comment by rjmacarthy** [comment]
Hey thanks for the report.  For some reason I cannot replicate this one either.  Do you have any concrete steps for replication?

**Comment by unclemusclez** [comment]
> Hey thanks for the report. For some reason I cannot replicate this one either. Do you have any concrete steps for replication?

@rjmacarthy  are you able to make a second embedding profile and have the pulldown-menu switch to it?

**Comment by rjmacarthy** [comment]
Hey @unclemusclez I just fixed this in a the latest version, sorry about that it was my mistake, thanks for reporting it!

**Comment by unclemusclez** [comment]
🐐
