### ISSUE TITLE
Stream doesnt close

### ISSUE THREAD

**Issue by dkpoulsen** [twinnydotdev/twinny#343]
**Describe the bug**
After updating to 3.17.20 I'm experiencing fim isnt working.

**Logging**
Request body:
{
  "model": "qwen2.5-coder:latest",
  "prompt": "<|fim_prefix|>const map = L.map('map').setView([56.2639, 9.5018], 7); // Center on Denmark\nconst loading = document.getElementById('loading');\nconst schoolCount = document.getElementById('schoolCount');\nconst filterButton = document.getElementById('filterButton');\nconst filterPopover = document.getElementById('filterPopover');\nconst instTypeFilters = document.getElementById('instTypeFilters');\nconst applyFiltersButton = document.getElementById('applyFilters');\n\nL.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {\n    attribution: '&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors'\n}).addTo(map);\n\nlet markers;\nlet allSchools;\n\nfilterButton.addEventListener('click', () => {\n    filterPopover.style.display = filterPopover.style.display === 'none' ? 'block' : 'none';\n});\n\nlet instTypes = [];\nlet kommuneList = [];\n\nfunction loadFilters() {\n    Promise.all([\n        fetch('/api/inst_types').then(response => response.json()),\n        fetch('/api/kommune_list').then(response => response.json())<|fim_suffix|>\n    ])\n        .then(([types, kommuner]) => {\n            instTypes = types;\n            kommuneList = kommuner;\n\n            $('#instTypeFilters').select2({\n                data: types.map(type => ({ id: type.inst_type_navn, text: type.inst_type_navn })),\n                placeholder: 'Select institution types',\n                allowClear: true\n            });\n\n            $('#kommuneFilters').select2({\n                data: kommuner.map(kommune => ({ id: kommune, text: kommune })),\n                placeholder: 'Select kommuner',\n                allowClear: true\n            });\n        })\n        .catch(error => {\n            console.error('Error loading filters:', error);\n            instTypeFilters.innerHTML = '<p>Error loading filters. Please try again later.</p>';\n            kommuneFilters.innerHTML = '<p>Error loading filters. Please try again later.</p>';\n        });\n}\n\nfunction loadSchools(filters = []) {\n    loading.style.display = 'block';\n    fetch('/api/school_locations')\n        .then(response => {\n            if (!response.ok) {\n                throw new Error('Network response was not ok');\n            }\n            return response.json();\n        })\n        .then(schools => {\n            allSchools = schools;\n            displayFilteredSchools(filters);\n        })\n        .catch(error => {\n            console.error('Error fetching school locations:', error);\n            schoolCount.textContent = 'Error loading school data';\n        })\n        .finally(() => {\n            loading.style.display = 'none';\n        });\n}\n\nfunction displayFilteredSchools(instTypeFilters, kommuneFilters) {\n    if (markers) {\n        map.removeLayer(markers);\n    }\n    markers = L.markerClusterGroup();\n\n    const filteredSchools = allSchools.filter(school => {\n        const instTypeMatch = instTypeFilters.length === 0 || instTypeFilters.includes(school.inst_type_navn);\n        const kommuneMatch = kommuneFilters.length === 0 || kommuneFilters.includes(school.adm_kommune_navn);\n        return instTypeMatch && kommuneMatch;\n    });\n\n    filteredSchools.forEach(school => {\n        markers.addLayer(L.marker([school.geo_bredde_grad, school.geo_laengde_grad])\n            .bindPopup(`<b>${school.inst_navn}</b><br>ID: ${school.id}<br>Type: ${school.inst_type_navn}<br>Kommune: ${school.adm_kommune_navn}<br><a href=\"#\" onclick=\"showSchoolDetails(${school.id}); return false;\">More details</a>`));\n    });\n    map.addLayer(markers);\n    schoolCount.textContent = `Total schools displayed: ${filteredSchools.length}`;\n\n    console.log('Filtered schools:', filteredSchools);\n    console.log('Applied inst_type filters:', instTypeFilters);\n    console.log('Applied kommune filters:', kommuneFilters);\n}\n\nfunction applyFilters() {\n    const selectedInstTypes = $('#instTypeFilters').val() || [];\n    const selectedKommuner = $('#kommuneFilters').val() || [];\n    displayFilteredSchools(selectedInstTypes, selectedKommuner);\n<|fim_middle|>",
  "stream": true,
  "keep_alive": "5m",
  "options": {
    "temperature": 0.2,
    "num_predict": 512
  }
}

Request options:
{
  "hostname": "0.0.0.0",
  "port": 11434,
  "path": "/api/generate",
  "protocol": "http",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": ""
  }
}

Number characters in all messages = undefined
09/10/2024 09:24:20 INFO *** Twinny completion triggered for file: file:///Volumes/External/Projects/schools/static/js/map.js ***
      Original completion: ```json
{
  "response": "error",
  "message": "The provided code snippet is incomplete and lacks the closing parenthesis for the Promise.all method. Please ensure that all parentheses are correctly matched and closed."
}
```
      Formatted completion: ```json
{
  "response": "error",
  "message": "The provided code snippet is incomplete and lacks the closing parenthesis for the Promise.all method. Please ensure that all parentheses are correctly matched and closed."
}
```

**API Provider**
Ollama local

**Chat or Auto Complete?**
chat works, but after fim is started it looks like the stream isnt closed, and blocks all interactions with Ollama.
GPU is also running at 100%

**Model Name**
Qwen2.5-coder 7b- instruct
**Desktop (please complete the following information):**
 - MacOS 15.0
Ollama 0.3.12

**Comment by rjmacarthy** [comment]
Hey @dkpoulsen seems you are using the instruct model for FIM, for Qwen you need to use the base models:

https://ollama.com/library/qwen2.5-coder:7b-base

**Comment by dkpoulsen** [comment]
thanks you right,
