### ISSUE TITLE
Embedding provider selection reverts to "default" one.

### ISSUE THREAD

**Issue by vkx86** [twinnydotdev/twinny#351]
**Describe the bug**
If there is more than one embedding provider the user's selection of second/third one reverts to "default" one.

**To Reproduce**
- re/install Twinny or reset providers to defaults
- add new embedding provider(s)
- go to chat view and click on "Embedding options" button
- enter and select newly created provider in "Embedding provider" combo
- navigate out of "Embedding provider" combo
- withing 1-3 sec. selection reverts to "default" one - the one that was initially created Twinny

**Expected behavior**
Embedding provider selection should be persisted per user's selection

**Screenshots**
[Screencast from 18-10-24 07:41:16.webm](https://github.com/user-attachments/assets/3b0de107-f1ea-4025-8c9a-ab1016f4bc61)

**Logging**
No logging was produced 

**API Provider**
Ollama/LMStudio, localhost with relevant ports 

**Model Name**
all-minilm:latest/nomic-embed-text-v1.5

**Desktop (please complete the following information):**
 - Ubuntu 22.04.5 LTS
 - Twinny v3.17.28

**Comment by rjmacarthy** [comment]
Thanks for the report, creating a new release which fixes it.
