### ISSUE TITLE
Trouble running with Windows Ollama

### ISSUE THREAD

**Issue by RandoOnSteam** [twinnydotdev/twinny#354]
Hi, I'm trying to get twinny running with ollama on windows. When it works it runs great, however it doesn't seem to work a lot of the time, and when it doesn't work it is basically impossible to figure out what is wrong. It really needs some feedback on what is happening in the setup stage after detecting ollama and running model. 

What happens is that it detects Ollama and the model it is running, but completion doesn't happen and when you send a chat nothing happens. I've tried turning on the log option but there are no logs output. I've just tried with the basic codellama. I checked the ollama logs and it seems to stop sending requests after the first one - maybe it gets stuck in a loop or something. My local openwebui works fine with ollama.
![untitled](https://github.com/user-attachments/assets/19d71b8f-284c-4847-9a00-e17072344898)

**Comment by RandoOnSteam** [comment]
A bit more info - it seems to be sending something off to ollama - here's the ollama log - the successful one on top is from a script I used to make sure /v1/chat/completions was working. Again there are no logs generated by twinny so I have no idea what it is doing outside of breaking out wireshark. I've tried both http/https etc..

[GIN] 2024/10/24 - 02:45:11 | 200 |    379.5247ms |       127.0.0.1 | POST     "/v1/chat/completions" <-- my script
[GIN] 2024/10/24 - 02:45:29 | 200 |      1.2039ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/10/24 - 02:45:43 | 404 |            0s |       127.0.0.1 | POST     "/v1/chat/completions" <-- 404 when twinny does it
--------- script for ref
from openai import OpenAI

client = OpenAI(
    base_url='http://localhost:11434/v1/',

    # required but ignored
    api_key='ollama',
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            'role': 'user',
            'content': 'Say this is a test',
        }
    ],
    model='codellama',
)

**Comment by rjmacarthy** [comment]
Hey, thanks for the report. If you open developer tools on vscode Help > Toggle Developer Tools there should be logs in there. Hope it helps. It's difficult for me to to help with support on an individual basis so let me know if that provides any idea into the problem. Many thanks.

**Comment by RandoOnSteam** [comment]
Understandable! Turns out this is user error. In the past I used only codellama:latest - now you have to fetch 7b-instruct and 7b-code both individually. Twinny wasn't respecting the model name I put in each - it was forcing 7b-instruct for chat and 7b-code for api/generate, which made debugging it a lot harder. Anyway, closing since it's user error - thanks! Sorry to waste your time.
