### ISSUE TITLE
Can't find module @lancedb/lancedb-win32-x64-msvc

### ISSUE THREAD

**Issue by fishshi** [twinnydotdev/twinny#364]
**Describe the bug**
<img width="326" alt="error" src="https://github.com/user-attachments/assets/3d02dc7e-dc14-41ef-bbe3-eb8ab5534469">

**To Reproduce**
clone the repository, run `npm install`, then Run Extension

**Desktop:**
 - OS: Windows11

**Additional context**
In Commit 62e5c2a, `@lancedb/lancedb-win32-x64-msvc` and many other modules are removed from `package-lock.json`. And I'm not sure about the cause and the potential impact it may have.

**Comment by fishshi** [comment]
https://github.com/twinnydotdev/twinny/commit/62e5c2adfd119da883b701c840a5dfdb90973fc2#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L2330

**Comment by rjmacarthy** [comment]
Thanks for the report, I reverted the change to the package-lock.json file, hopefully it will be resolved now.
