### ISSUE TITLE
FIM autocomplete format not being changed correctly

### ISSUE THREAD

**Issue by paryska99** [twinnydotdev/twinny#377]
When using twinny with Codestral with ollama, the FIM template that's being used seems to be the llama template.

There doesn't seem to be any way to manually set the correct template for Codestral/create own FIM template for autocompletion, even though I see Codestral being hardcoded into the plugin itself.

I propose a setting to choose from the available hardcoded autocomplete FIM templates in the settings or a way to create own autocomplete FIM template.
(note: changing the templates through "manage twinny templates" didn't really seem to change anything for autocomplete)

**Comment by rjmacarthy** [comment]
Hey you should be able to edit `fim.hbs` and use `custom` as the template in the provider settings.

**Comment by paryska99** [comment]
Thank you so much, i didn't know about the existence of the setting there. Exactly what I was looking for, I'll get to testing now :)
