### ISSUE TITLE
Errors occur when using Twinny and certain AI extensions (such as FitenCode) in Vscode together

### ISSUE THREAD

**Issue by ZhongGuangshen** [twinnydotdev/twinny#391]
**Describe the bug**
When you have installed and enabled certain AI extensions _(**such as FittenCode**)_ in Vscode, running the Twinny extension (_**whether it is the source code on GitHub or the plugin on Vscode**_) will result in an error: **Twinny's display interface cannot successfully display Ollama's return content, but will directly display an error “First parameter has member 'readable' that is not a ReadableStream. ” after a brief thought (in some cases, it will also stuck on displaying Thinking, especially when you try to correct it based on online cases)**

**To Reproduce**
Simply download extensions such as Fitten Code in your Vscode and enable it, then enable or run your Twinny extension at the same time
![屏幕截图 2024-11-14 191434](https://github.com/user-attachments/assets/2aed5740-b3c8-4284-ba68-7f401efadda6)

Start Olama serve, ask it anything and you will find that Ollama serve will receive your API call normally and respond, but Twinny's dialog box will remain stuck in Thinking, If you are using the plugin source code on GitHub, you will find that the debugging console will console.error: **_'First parameter has member 'readable' that is not a ReadableStream'_** If you disable AI plugins such as FittenCode and try again, you will find that the Twinny plugin has no problem implementing normal conversations
![thefirst](https://github.com/user-attachments/assets/fd577dc5-a072-44c6-8a53-c2212c3b01b5)

**Expected behavior**
Twinny can use other stream processing methods or compatibility methods to ensure that its own Q&A is not affected when _**ReadableStream**_ is affected by AI plugins such as **_FittenCode_**, or when **_ReadableStream_** reports an error, **_FittenCode_** can directly pop up a pop-up window to explain the current problem and advise users to turn off AI plugins that cause interference

**Screenshots**

**Logging**
![屏幕截图 2024-11-14 191030](https://github.com/user-attachments/assets/839b952b-8adb-4a42-be83-b7d5a044976a)

 TypeError: First parameter has member 'readable' that is not a ReadableStream.
	at hn (c:\Users\Administrator\.vscode\extensions\fittentech.fitten-code-0.10.96\extension\dist\extension.js:115:8213)
	at c:\Users\Administrator\.vscode\extensions\fittentech.fitten-code-0.10.96\extension\dist\extension.js:115:56256
	at h.pipeThrough (c:\Users\Administrator\.vscode\extensions\fittentech.fitten-code-0.10.96\extension\dist\extension.js:115:56448)
	at streamResponse (c:\twinny\fix_code\twinny\src\extension\api.ts:44:8)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {stack: "TypeError: First parameter has member 'readab…ions (node:internal/process/task_queues:95:5)", message: "First parameter has member 'readable' that is not a ReadableStream."}

**API Provider**
I only tested the Ollama one 

**Additional context**
And I am also quite interested in another question: why did I find that Ollama accepted 3 questions at once when I first started Twinny asking Ollama a question? And if there is an error, the console will also display 3 error messages

**Comment by ZhongGuangshen** [comment]
At first, I planned to directly solve this error. To do so, I referred to other online projects such as Vercel/ai on GitHub and focused on [this article](https://github.com/vercel/ai/issues/199) in Vercel/ai. Then, I tried to solve the problem using Nodejs compatibility using the Compat method mentioned in it, but it still failed:  If I had modified the scripts according to his Compat method here, there would be no error in console log, but the conversations will just stuck in `Thinking...` This is undoubtedly a failed repair

That is to say, utilizing the approach proposed by `Mindlight`
![屏幕截图 2024-11-14 194522](https://github.com/user-attachments/assets/228943f9-774e-442f-963e-a427a8db8c81)
![屏幕截图 2024-11-14 194530](https://github.com/user-attachments/assets/4c890c48-92a2-4f46-91a7-45d96b767ee1)

**Comment by yuzcat01** [comment]
It seems that the best way to solve this problem is to close other similar AI plugins, this error I have seen in issues of other types of projects, such as [continue](https://github.com/continuedev/continue).

**Comment by ZhongGuangshen** [comment]
In addition, I have also tried using **node-fetch**  instead of **fetch** or using **http/https methods** instead of **fetch**, but they have not worked out and **ReadableStream errors** still occur.

**Comment by rjmacarthy** [comment]
Thanks for this, your PR has been merged and released, please check and close if applicable.

Many thanks!
