### ISSUE TITLE
Random blabbering Nonsense

### ISSUE THREAD

**Issue by Dejon141** [twinnydotdev/twinny#413]
**Describe the bug**
 randomly blabbering

**Expected behavior**.
supposed to write code and autocomplete suggestions in fim

**Screenshots**
![image](https://github.com/user-attachments/assets/a734fc36-ce63-4e0f-b826-7ee2bf01d9e5)

**API Provider**
I use Ollama

**Chat or Auto Complete?**
Auto complete

**Model Name**
Provide the model name you are using e.g `codellama:7b-code` or `codellama:7b-instruct`

**Desktop:"
-Windows

**Additional context**
Happens on both of my computer with what ever model i use spouting out random nonsense not related to code. I use nomic embedding and llama3.2 for chat

**Comment by rjmacarthy** [comment]
Hey thanks for the report. Usually this is due to mis-configuration and/or wrong model usage for specific tasks, please refer to documentation for recommended models and settings.

Many thanks!
